### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by madiedgar** [legesher/language-legesher-python#13]
Add a `CONTRIBUTING.md` file in the root of the repository that contains this content:

```md
See the [Legesher contributing guide](https://github.com/legesher/legesher/blob/master/CONTRIBUTING.md)
```

Simple enough 👍 Please ask to be assigned to this issue so we don't have duplicates 😄

**Comment by imgovind** [comment]
Can I be assigned to this?

**Comment by madiedgar** [comment]
Absolutely @imgovind, I'll assign you to it!
