### ISSUE TITLE
style: add Unibeautify from pylint

### ISSUE THREAD

**Issue by madiedgar** [legesher/language-legesher-python#16]
## Add Unibeautify Linting 

Being able to have formatted code that is aligned with the style guide is extremely important, not just for learning best practices but for the future of this project.

_This repository currently has a `.pylint` file. _ As we are moving all of our repositories to use unibeautify, we want to incorporate this into the new linting config.

- [ ] Please add a `.unibeautifyrc.json` file with a linting configuration to match the languages used within this repository and the `.pylint`
- [ ] Please correct the current files to match the linting configurations (this should be in the details after you commit the first task^

**Comment by Pieterv24** [comment]
Is this still available? If so can I pick up this issue?

**Comment by bhadreshpsavani** [comment]
Can i work on this issue?

**Comment by madiedgar** [comment]
Yes @bhadreshpsavani, would love your help on this!

**Comment by bhadreshpsavani** [comment]
Hello @madiedgar,

Will these lines
```
"Python": {
    	"beautifiers": [
      		"Black",
     		"YAPF",
		"autopep8", 
		"pybeautifier"
    	]},
"CoffeeScript":{
	"beautifiers":[
		"coffee-fmt",
		"CoffeeFormatter"]
	}
```
be enough for our project in .unibeautifyrc.json file?

How can I relate .pylint with .unibeautifyrc.json so that I can configure .unibeautifyrc.json from .pylint?

what other files do I need to configure for these changes?

Sorry for the questions, Since I have never worked on this before and unable to find many resources I got a couple of questions.

**Comment by madiedgar** [comment]
These are wonderful questions! That looks wonderful! 👏 

Thanks so much for trying to incorporate the linter. Adding Python into `.unibeautifyrc.json` is great 👌. If the two linting configs end up conflicting when you're formatting a python file then let's stick with the `.unibeautifyrc.json` for consistency sake across the organization.

**Comment by madiedgar** [comment]
Closing this issue as linting was added in #19 Thank you for your help in guiding this issue!  👍
