### ISSUE TITLE
marketing: add project to "awesome-for-beginners"

### ISSUE THREAD

**Issue by madiedgar** [legesher/language-legesher-python#5]
## Awesome-For-Beginners

Would love to add this repository to the python section for the [`awesome-for-beginners`](https://github.com/MunGell/awesome-for-beginners#python) repository for new programmers / open sourcers to learn about contributing to Legesher. 

Please use label: `good-first-issue` or `Opportunity: Technical Beginner`. More details can be found in their pull request template.

**Comment by sdesani** [comment]
Added a PR for same - https://github.com/MunGell/awesome-for-beginners/pull/421

**Comment by madiedgar** [comment]
Thank you @sdesani for your contribution! 🎉🎉🎉 ❤️ THANK YOU THANK YOU THANK YOU ❤️ We'd love to celebrate you and your contribution to the community. Let us say "Thank You" again, by sending you a [special gift](https://madi357705.typeform.com/to/wzub4R)!

We couldn't thank you enough for your contribution. We hope you continue sharing your gifts and knowledge with not just us, but with the world around you.😍

Also - I'm adding `allcontributors` to the project, so you can get credit for this within our project as well (and get you another pull request!). I'll update you when that's configured 😄
