### ISSUE TITLE
marketing: add repository to "awesome-for-non-programmers"

### ISSUE THREAD

**Issue by madiedgar** [legesher/language-legesher-python#6]
## Awesome-For-Non-Programmers

Would love to add this repository to the [`awesome-for-non-programmers`](https://github.com/szabgab/awesome-for-non-programmers) repository for non programmers to learn about open source opportunities that don't require a technical background. 

With the Legesher project, there are a lot of opportunities for people of all backgrounds to contribute the skills they either want to grow in or give back. With a strong emphasis on written language translation, individuals who are bilingual have a great space to contribute. Individuals who want to grow in community development, marketing, writing impactful pieces of insight, or just want to learn more about the tech world have ample amounts of opportunities here as well! 

More details can be found in their pull request template.

**Comment by sdesani** [comment]
@madiedgar, created a PR for same - https://github.com/MunGell/awesome-for-beginners/pull/421

**Comment by sdesani** [comment]
@madiedgar my bad. I meant to tag the other issue. #5. I added it to Awesome-For-Beginners repo.

**Comment by madiedgar** [comment]
This is amazing!! Thank you so much @sdesani for your contribution!! I'm adding `allcontributors` to the project, so you can get credit for pull requests on other projects within our project as well (and get you another pull request!). I'll update you when that's configured 😄 Thanks again!!

**Comment by madiedgar** [comment]
Closing this issue as the maintainer of `awesome-for-non-programmers` won't accept the pull requests. [see here](https://github.com/legesher/legesher/issues/54)
